### ISSUE TITLE
Compacting switch statement 

### ISSUE THREAD

**Issue by andulica** [andulica/CalculateAreaExercise#1]
How can I get rid of the repetitive code that is in the switch statement and create just one line that will serve for all shapes. 
For example the lines where I calculate the total price for labour I can't see how I can compact the code in such way that instead of writing in all cases, I could write just one Console.WriteLine where it can be used by all cases. I know that I can use methods but is it ok to use them in this context ?

**Comment by andulica** [comment]
[https://github.com/andulica/CalculateAreaExercise/blob/9a43758fa2dd696c3f8b5d27daf24516030f9fd3/Program.cs#L37](url)

**Comment by incredibleLeitman** [comment]
Usually, if you want to execute the same code in every case (or condition) you just can put the duplicated code below your switch statement.

Keep in mind though, that variables only live within the scope they are declared 👆 

So if you want to access the same variable in your cases and after the switch you need to declare it before that

**Comment by andulica** [comment]
Let's say that I want to get rid of this duplicate code that is present in all cases: 
https://github.com/andulica/CalculateAreaExercise/blob/9a43758fa2dd696c3f8b5d27daf24516030f9fd3/Program.cs#L31-L32

I will put it outside the switch statement but it will need the double variable totalPriceForMaterials extracted from the case statement and put in on a new Console.WriteLine and I will need to do it for each case because they are all dependant on the calculation done in each case ... I hope that it makes sense what I want to say. if not, can you show me an example of what you would do in the highlighted case please ? 

Thanks

**Comment by andulica** [comment]
I will try to make a better point of what I truly mean. 
If I need to get all the variables resulted from the calculations of the area from all cases and print the message for each one of them of what they represent e.g :
case (rectangle) 
                        {
                        double totalPriceForMaterialsRectangle = priceOfFlooring * areaRectangle;
                        return totalPriceForMaterialsRectangle; 
                        break;
                        }

Console.WriteLine("Total price for materials is :" + totalpriceForMaterialsRectangle)

then what is the point of getting rid of the duplicate code inside the switch statement if I will need create, outside the switch statement , a print line for each total price for materials. Hope it makes sense . Even I am getting confused :((

**Comment by incredibleLeitman** [comment]
Sorry, I don't exactly understand your point there :S

But the basic idea is, that you should only have code that is really dependent on the given choice in each case and common code before or after your switch.

So in this exercise only the calculation of the area is dependent on the choice by using another formula,
all the other stuff like asking for price, calculation hours of flooring etc... is common and the same for all shapes.



Also I think this issue is basically just an discussion about #3 right?

**Comment by incredibleLeitman** [comment]
btw above code
```
case (rectangle)
{
  double totalPriceForMaterialsRectangle = priceOfFlooring * areaRectangle;
  return totalPriceForMaterialsRectangle;
  break;
}
```
may not work a you expect 👆 
the "break" statement makes your code "jump out" of a loop or a switch case, continuing with the block after this loop or switch.
A "return" on the other hand jumps out of the whole function, leaving all remaining blocks aside. As the first few exercises only happen in the main function, having a "return anything;" in there just closes your application
